---
- name: Delete RoleBinding for user accounts if they exist
  k8s:
    namespace: '{{ jenkins_project_name }}'
    definition: '{{ lookup("template", "jenkins_user_role_binding.yml.j2")|from_yaml }}'
    state: absent

- name: Add RoleBinding for user accounts
  k8s:
    namespace: '{{ jenkins_project_name }}'
    definition: '{{ lookup("template", "jenkins_user_role_binding.yml.j2")|from_yaml }}'

- name: Create run-as-user-1001 SCC for jenkins
  k8s:
    definition: "{{ lookup('template', 'rbac.yml.j2') | from_yaml }}"

- name: Wait for Jenkins to respond to requests
  uri:
    url: 'https://jenkins-{{ tssc_namespace }}.apps.{{ full_cluster_name }}/login'
    validate_certs: no
  register: jenkins_endpoint
  until: jenkins_endpoint.status == 200
  retries: 30
  delay: 20

- name: Get Service Account token
  set_fact:
    ocp_token: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"

- name: Ensure Gitea Server is configured in jenkins settings
  uri:
    url: 'https://jenkins-{{ tssc_namespace }}.apps.{{ full_cluster_name }}/script'
    method: POST
    body_format: form-urlencoded
    validate_certs: false
    headers:
      Authorization: 'Bearer {{ ocp_token }}'
    body:
      script: 'giteaServers = Jenkins.instance.getExtensionList(org.jenkinsci.plugin.gitea.servers.GiteaServers.class)[0];giteaServers.updateServer(new org.jenkinsci.plugin.gitea.servers.GiteaServer("platform", "http://gitea.{{ tssc_namespace }}.svc.cluster.local:3000", true, null, "https://gitea-{{ tssc_namespace }}.apps.{{ full_cluster_name }}/"));giteaServers.save();["BranchSpec getName", "GitSCM getBranches", "GitSCM getUserRemoteConfigs", "UserRemoteConfig getUrl"].each{ method -> org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval.get().approveSignature("method hudson.plugins.git.${method}")}'
  register: org_response

- name: Get gitea token secret
  k8s_info:
    kind: Secret
    api_version: v1
    namespace: '{{ tssc_namespace }}'
    name: gitea-access-token
  register: gitea_token_secret

- set_fact:
    gitea_token: "{{ gitea_token_secret.resources[0].data.token | b64decode }}"

- name: Create Gitea Credential
  uri:
    url: "https://jenkins-{{ tssc_namespace }}.apps.{{ full_cluster_name }}/credentials/store/system/domain/_/createCredentials"
    method: POST
    validate_certs: false
    headers:
      Authorization: 'Bearer {{ ocp_token }}'
      Content-Type: 'text/xml'
    body: "{{ lookup('template', 'gitea-token-credential.xml.j2') }}"
    status_code: 200,409
  register: credential_response
  changed_when: credential_response.status == 200

- name: Create platform Gitea Organization
  uri:
    url: 'https://jenkins-{{ tssc_namespace }}.apps.{{ full_cluster_name }}/createItem?name=platform'
    method: POST
    validate_certs: false
    headers:
      Authorization: 'Bearer {{ ocp_token }}'
      Content-Type: 'text/xml'
    body: "{{ lookup('template', 'gitea-organization.xml.j2') }}"
    status_code: 200,400
  register: org_response
  changed_when: org_response.status == 200
